[package]
name = "escrow-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
escrow-api.workspace = true
num-bigint = {version = "0.4.6", features = ["rand"]}
solana-program.workspace = true
spl-associated-token-account.workspace = true
spl-token.workspace = true
steel.workspace = true

[dev-dependencies]
bs64 = "0.1.2"
rand = "0.8.5"
solana-program-test = "1.18"
solana-sdk = "1.18"
tokio = { version = "1.35", features = ["full"] }
